services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.postgrest
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: ${PG_CONNECTION_STRING}
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: web_anon

  swagger:
    build:
      context: .
      dockerfile: Dockerfile.swagger
    ports:
      - "8080:8080"
    environment:
      API_URL: http://localhost:3000/
    depends_on:
      - server
